name: Static Resource Deployment Pipeline

on:
  workflow_dispatch:
    inputs:
      target_environment:
        description: 'Select the target environment for deployment'
        required: true
        type: choice
        options:
          - 'int'
          - 'qa'
          - 'training'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v4
        with:
          ref: 'main'
          path: 'app'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify existence of target application file
        id: verify_target_file
        run: |
          TARGET_APP_FILE_PATH="${GITHUB_WORKSPACE}/app/${{ github.event.inputs.target_environment }}.zip"
          if [ ! -f "$TARGET_APP_FILE_PATH" ]; then
            echo "::error file=$TARGET_APP_FILE_PATH::Error: The target application file does not exist."
            exit 1
          fi
        shell: bash

      - name: Install Salesforce CLI
        if: steps.verify_target_file.outcome == 'success'
        run: |
          echo "Starting installation of Salesforce CLI..."
          
          SALESFORCE_CLI_INSTALL_DIR="${GITHUB_WORKSPACE}/sf-cli"
          mkdir -p $SALESFORCE_CLI_INSTALL_DIR

          SALESFORCE_CLI_DOWNLOAD_URL="https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz"
          curl -L $SALESFORCE_CLI_DOWNLOAD_URL | tar -xJf - -C $SALESFORCE_CLI_INSTALL_DIR

          if [ -f "$SALESFORCE_CLI_INSTALL_DIR/sf/bin/sf" ]; then
            echo "Salesforce CLI installed successfully in $SALESFORCE_CLI_INSTALL_DIR."
          else
            echo "::error::Salesforce CLI installation failed or directory structure is incorrect."
            exit 1
          fi

          echo "$SALESFORCE_CLI_INSTALL_DIR/sf/bin" >> $GITHUB_PATH
        shell: bash

      - name: Display Salesforce CLI version
        if: steps.verify_target_file.outcome == 'success'
        run: |
          sf version
        shell: bash

        